### ISSUE TITLE
entrypoint.sh: No such file or directory[BUG] <title>

### ISSUE THREAD

**Issue by chanansh** [tj-actions/coverage-badge-py#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

```
Run pip install -U coverage-badge
Collecting coverage-badge
  Downloading coverage_badge-1.1.0-py2.py3-none-any.whl (6.4 kB)
Collecting coverage
  Downloading coverage-6.3.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 KB 10.3 MB/s eta 0:00:00
Installing collected packages: coverage, coverage-badge
Successfully installed coverage-6.3.2 coverage-badge-1.1.0
bash: entrypoint.sh: No such file or directory
Error: Process completed with exit code 127.
```

### To Reproduce

just add the action to the workflow

### What OS are you seeing the problem on?

macos-11

### Expected behavior?

run coverage

### Relevant log output

```shell
see above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@chanansh Sorry for the late response this should be fixed in the latest release.
